//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Linkout.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LinkoutEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LinkoutEntities object using the connection string found in the 'LinkoutEntities' section of the application configuration file.
        /// </summary>
        public LinkoutEntities() : base("name=LinkoutEntities", "LinkoutEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LinkoutEntities object.
        /// </summary>
        public LinkoutEntities(string connectionString) : base(connectionString, "LinkoutEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LinkoutEntities object.
        /// </summary>
        public LinkoutEntities(EntityConnection connection) : base(connection, "LinkoutEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FG_COSTCO_PRODUCTS> FG_COSTCO_PRODUCTS
        {
            get
            {
                if ((_FG_COSTCO_PRODUCTS == null))
                {
                    _FG_COSTCO_PRODUCTS = base.CreateObjectSet<FG_COSTCO_PRODUCTS>("FG_COSTCO_PRODUCTS");
                }
                return _FG_COSTCO_PRODUCTS;
            }
        }
        private ObjectSet<FG_COSTCO_PRODUCTS> _FG_COSTCO_PRODUCTS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FG_COSTCO_PRODUCTS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFG_COSTCO_PRODUCTS(FG_COSTCO_PRODUCTS fG_COSTCO_PRODUCTS)
        {
            base.AddObject("FG_COSTCO_PRODUCTS", fG_COSTCO_PRODUCTS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Linkout.Data", Name="FG_COSTCO_PRODUCTS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FG_COSTCO_PRODUCTS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FG_COSTCO_PRODUCTS object.
        /// </summary>
        /// <param name="fG_PROD_ID">Initial value of the FG_PROD_ID property.</param>
        /// <param name="fG_PROD_CODE">Initial value of the FG_PROD_CODE property.</param>
        /// <param name="fG_DESCRIPTION">Initial value of the FG_DESCRIPTION property.</param>
        /// <param name="fG_PRICE">Initial value of the FG_PRICE property.</param>
        /// <param name="fG_ACTIVE_FLAG">Initial value of the FG_ACTIVE_FLAG property.</param>
        public static FG_COSTCO_PRODUCTS CreateFG_COSTCO_PRODUCTS(global::System.Decimal fG_PROD_ID, global::System.String fG_PROD_CODE, global::System.String fG_DESCRIPTION, global::System.Decimal fG_PRICE, global::System.String fG_ACTIVE_FLAG)
        {
            FG_COSTCO_PRODUCTS fG_COSTCO_PRODUCTS = new FG_COSTCO_PRODUCTS();
            fG_COSTCO_PRODUCTS.FG_PROD_ID = fG_PROD_ID;
            fG_COSTCO_PRODUCTS.FG_PROD_CODE = fG_PROD_CODE;
            fG_COSTCO_PRODUCTS.FG_DESCRIPTION = fG_DESCRIPTION;
            fG_COSTCO_PRODUCTS.FG_PRICE = fG_PRICE;
            fG_COSTCO_PRODUCTS.FG_ACTIVE_FLAG = fG_ACTIVE_FLAG;
            return fG_COSTCO_PRODUCTS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FG_PROD_ID
        {
            get
            {
                return _FG_PROD_ID;
            }
            set
            {
                if (_FG_PROD_ID != value)
                {
                    OnFG_PROD_IDChanging(value);
                    ReportPropertyChanging("FG_PROD_ID");
                    _FG_PROD_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FG_PROD_ID");
                    OnFG_PROD_IDChanged();
                }
            }
        }
        private global::System.Decimal _FG_PROD_ID;
        partial void OnFG_PROD_IDChanging(global::System.Decimal value);
        partial void OnFG_PROD_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FG_LEATHER_ROWS
        {
            get
            {
                return _FG_LEATHER_ROWS;
            }
            set
            {
                OnFG_LEATHER_ROWSChanging(value);
                ReportPropertyChanging("FG_LEATHER_ROWS");
                _FG_LEATHER_ROWS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FG_LEATHER_ROWS");
                OnFG_LEATHER_ROWSChanged();
            }
        }
        private Nullable<global::System.Decimal> _FG_LEATHER_ROWS;
        partial void OnFG_LEATHER_ROWSChanging(Nullable<global::System.Decimal> value);
        partial void OnFG_LEATHER_ROWSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FG_SEAT_HEATERS
        {
            get
            {
                return _FG_SEAT_HEATERS;
            }
            set
            {
                OnFG_SEAT_HEATERSChanging(value);
                ReportPropertyChanging("FG_SEAT_HEATERS");
                _FG_SEAT_HEATERS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FG_SEAT_HEATERS");
                OnFG_SEAT_HEATERSChanged();
            }
        }
        private Nullable<global::System.Decimal> _FG_SEAT_HEATERS;
        partial void OnFG_SEAT_HEATERSChanging(Nullable<global::System.Decimal> value);
        partial void OnFG_SEAT_HEATERSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FG_PROD_CODE
        {
            get
            {
                return _FG_PROD_CODE;
            }
            set
            {
                OnFG_PROD_CODEChanging(value);
                ReportPropertyChanging("FG_PROD_CODE");
                _FG_PROD_CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FG_PROD_CODE");
                OnFG_PROD_CODEChanged();
            }
        }
        private global::System.String _FG_PROD_CODE;
        partial void OnFG_PROD_CODEChanging(global::System.String value);
        partial void OnFG_PROD_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FG_DESCRIPTION
        {
            get
            {
                return _FG_DESCRIPTION;
            }
            set
            {
                OnFG_DESCRIPTIONChanging(value);
                ReportPropertyChanging("FG_DESCRIPTION");
                _FG_DESCRIPTION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FG_DESCRIPTION");
                OnFG_DESCRIPTIONChanged();
            }
        }
        private global::System.String _FG_DESCRIPTION;
        partial void OnFG_DESCRIPTIONChanging(global::System.String value);
        partial void OnFG_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FG_PRICE
        {
            get
            {
                return _FG_PRICE;
            }
            set
            {
                OnFG_PRICEChanging(value);
                ReportPropertyChanging("FG_PRICE");
                _FG_PRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FG_PRICE");
                OnFG_PRICEChanged();
            }
        }
        private global::System.Decimal _FG_PRICE;
        partial void OnFG_PRICEChanging(global::System.Decimal value);
        partial void OnFG_PRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FG_ACTIVE_FLAG
        {
            get
            {
                return _FG_ACTIVE_FLAG;
            }
            set
            {
                OnFG_ACTIVE_FLAGChanging(value);
                ReportPropertyChanging("FG_ACTIVE_FLAG");
                _FG_ACTIVE_FLAG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FG_ACTIVE_FLAG");
                OnFG_ACTIVE_FLAGChanged();
            }
        }
        private global::System.String _FG_ACTIVE_FLAG;
        partial void OnFG_ACTIVE_FLAGChanging(global::System.String value);
        partial void OnFG_ACTIVE_FLAGChanged();

        #endregion
    
    }

    #endregion
    
}
