//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace ComHub {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ConfirmMessageBatch {
        
        private partnerID partnerIDField;
        
        private hubConfirm[] hubConfirmField;
        
        private string messageCountField;
        
        private string typeField;
        
        private string batchNumberField;
        
        /// <remarks/>
        public partnerID partnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hubConfirm")]
        public hubConfirm[] hubConfirm {
            get {
                return this.hubConfirmField;
            }
            set {
                this.hubConfirmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string messageCount {
            get {
                return this.messageCountField;
            }
            set {
                this.messageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string batchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class partnerID {
        
        private string nameField;
        
        private partnerIDRoleType roleTypeField;
        
        private bool roleTypeFieldSpecified;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public partnerIDRoleType roleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool roleTypeSpecified {
            get {
                return this.roleTypeFieldSpecified;
            }
            set {
                this.roleTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum partnerIDRoleType {
        
        /// <remarks/>
        vendor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class hubConfirm {
        
        private participatingParty participatingPartyField;
        
        private string partnerTrxIDField;
        
        private string partnerTrxDateField;
        
        private string poNumberField;
        
        private trxData trxDataField;
        
        private hubAction[] hubActionField;
        
        private packageDetail[] packageDetailField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public participatingParty participatingParty {
            get {
                return this.participatingPartyField;
            }
            set {
                this.participatingPartyField = value;
            }
        }
        
        /// <remarks/>
        public string partnerTrxID {
            get {
                return this.partnerTrxIDField;
            }
            set {
                this.partnerTrxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string partnerTrxDate {
            get {
                return this.partnerTrxDateField;
            }
            set {
                this.partnerTrxDateField = value;
            }
        }
        
        /// <remarks/>
        public string poNumber {
            get {
                return this.poNumberField;
            }
            set {
                this.poNumberField = value;
            }
        }
        
        /// <remarks/>
        public trxData trxData {
            get {
                return this.trxDataField;
            }
            set {
                this.trxDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hubAction")]
        public hubAction[] hubAction {
            get {
                return this.hubActionField;
            }
            set {
                this.hubActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("packageDetail")]
        public packageDetail[] packageDetail {
            get {
                return this.packageDetailField;
            }
            set {
                this.packageDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class participatingParty {
        
        private participatingPartyName nameField;
        
        private bool nameFieldSpecified;
        
        private participatingPartyRoleType roleTypeField;
        
        private bool roleTypeFieldSpecified;
        
        private participatingPartyParticipationCode participationCodeField;
        
        private bool participationCodeFieldSpecified;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public participatingPartyName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nameSpecified {
            get {
                return this.nameFieldSpecified;
            }
            set {
                this.nameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public participatingPartyRoleType roleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool roleTypeSpecified {
            get {
                return this.roleTypeFieldSpecified;
            }
            set {
                this.roleTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public participatingPartyParticipationCode participationCode {
            get {
                return this.participationCodeField;
            }
            set {
                this.participationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool participationCodeSpecified {
            get {
                return this.participationCodeFieldSpecified;
            }
            set {
                this.participationCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum participatingPartyName {
        
        /// <remarks/>
        Costco,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum participatingPartyRoleType {
        
        /// <remarks/>
        merchant,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum participatingPartyParticipationCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("To:")]
        To,
        /// <summary>
        /// I had to add this manually after creating this with xsd.exe. It did not incorporate both allawable values
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("From:")]
        From,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class trxData {
        
        private string vendorsInvoiceNumberField;
        
        /// <remarks/>
        public string vendorsInvoiceNumber {
            get {
                return this.vendorsInvoiceNumberField;
            }
            set {
                this.vendorsInvoiceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class hubAction {
        
        private action actionField;
        
        private string actionCodeField;
        
        private string merchantLineNumberField;
        
        private string trxVendorSKUField;
        
        private string trxMerchantSKUField;
        
        private string trxQtyField;
        
        private packageDetailLink[] packageDetailLinkField;
        
        private string transactionItemIDField;
        
        /// <remarks/>
        public action action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string merchantLineNumber {
            get {
                return this.merchantLineNumberField;
            }
            set {
                this.merchantLineNumberField = value;
            }
        }
        
        /// <remarks/>
        public string trxVendorSKU {
            get {
                return this.trxVendorSKUField;
            }
            set {
                this.trxVendorSKUField = value;
            }
        }
        
        /// <remarks/>
        public string trxMerchantSKU {
            get {
                return this.trxMerchantSKUField;
            }
            set {
                this.trxMerchantSKUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string trxQty {
            get {
                return this.trxQtyField;
            }
            set {
                this.trxQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("packageDetailLink")]
        public packageDetailLink[] packageDetailLink {
            get {
                return this.packageDetailLinkField;
            }
            set {
                this.packageDetailLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionItemID {
            get {
                return this.transactionItemIDField;
            }
            set {
                this.transactionItemIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum action {
        
        /// <remarks/>
        v_ship,
        
        /// <remarks/>
        v_cancel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class packageDetailLink {
        
        private string packageDetailIDField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string packageDetailID {
            get {
                return this.packageDetailIDField;
            }
            set {
                this.packageDetailIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class packageDetail {
        
        private string shipDateField;
        
        private string serviceLevel1Field;
        
        private string trackingNumberField;
        
        private shippingWeight shippingWeightField;
        
        private string packageDetailIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string shipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        public string serviceLevel1 {
            get {
                return this.serviceLevel1Field;
            }
            set {
                this.serviceLevel1Field = value;
            }
        }
        
        /// <remarks/>
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public shippingWeight shippingWeight {
            get {
                return this.shippingWeightField;
            }
            set {
                this.shippingWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string packageDetailID {
            get {
                return this.packageDetailIDField;
            }
            set {
                this.packageDetailIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class shippingWeight {
        
        private shippingWeightWeightUnit weightUnitField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public shippingWeightWeightUnit weightUnit {
            get {
                return this.weightUnitField;
            }
            set {
                this.weightUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum shippingWeightWeightUnit {
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        OZ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OrderMessageBatch {
        
        private partnerID partnerIDField;
        
        private hubOrder[] hubOrderField;
        
        private string messageCountField;
        
        private string batchNumberField;
        
        /// <remarks/>
        public partnerID partnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hubOrder")]
        public hubOrder[] hubOrder {
            get {
                return this.hubOrderField;
            }
            set {
                this.hubOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string messageCount {
            get {
                return this.messageCountField;
            }
            set {
                this.messageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string batchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class hubOrder {
        
        private participatingParty[] participatingPartyField;
        
        private string sendersIdForReceiverField;
        
        private string orderIdField;
        
        private string lineCountField;
        
        private string poNumberField;
        
        private string orderDateField;
        
        private shipTo shipToField;
        
        private billTo billToField;
        
        private string shippingCodeField;
        
        private string custOrderNumberField;
        
        private poHdrData poHdrDataField;
        
        private lineItem[] lineItemField;
        
        private personPlace[] personPlaceField;
        
        private hubOrderType typeField;
        
        private bool typeFieldSpecified;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participatingParty")]
        public participatingParty[] participatingParty {
            get {
                return this.participatingPartyField;
            }
            set {
                this.participatingPartyField = value;
            }
        }
        
        /// <remarks/>
        public string sendersIdForReceiver {
            get {
                return this.sendersIdForReceiverField;
            }
            set {
                this.sendersIdForReceiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string lineCount {
            get {
                return this.lineCountField;
            }
            set {
                this.lineCountField = value;
            }
        }
        
        /// <remarks/>
        public string poNumber {
            get {
                return this.poNumberField;
            }
            set {
                this.poNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string orderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public shipTo shipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        public billTo billTo {
            get {
                return this.billToField;
            }
            set {
                this.billToField = value;
            }
        }
        
        /// <remarks/>
        public string shippingCode {
            get {
                return this.shippingCodeField;
            }
            set {
                this.shippingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string custOrderNumber {
            get {
                return this.custOrderNumberField;
            }
            set {
                this.custOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public poHdrData poHdrData {
            get {
                return this.poHdrDataField;
            }
            set {
                this.poHdrDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineItem")]
        public lineItem[] lineItem {
            get {
                return this.lineItemField;
            }
            set {
                this.lineItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personPlace")]
        public personPlace[] personPlace {
            get {
                return this.personPlaceField;
            }
            set {
                this.personPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public hubOrderType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class shipTo {
        
        private string personPlaceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string personPlaceID {
            get {
                return this.personPlaceIDField;
            }
            set {
                this.personPlaceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class billTo {
        
        private string personPlaceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string personPlaceID {
            get {
                return this.personPlaceIDField;
            }
            set {
                this.personPlaceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class poHdrData {
        
        private string reqShipDateField;
        
        private packListData packListDataField;
        
        private string custOrderNumberField;
        
        private poTypeCode poTypeCodeField;
        
        private bool poTypeCodeFieldSpecified;
        
        private string giftMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string reqShipDate {
            get {
                return this.reqShipDateField;
            }
            set {
                this.reqShipDateField = value;
            }
        }
        
        /// <remarks/>
        public packListData packListData {
            get {
                return this.packListDataField;
            }
            set {
                this.packListDataField = value;
            }
        }
        
        /// <remarks/>
        public string custOrderNumber {
            get {
                return this.custOrderNumberField;
            }
            set {
                this.custOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public poTypeCode poTypeCode {
            get {
                return this.poTypeCodeField;
            }
            set {
                this.poTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poTypeCodeSpecified {
            get {
                return this.poTypeCodeFieldSpecified;
            }
            set {
                this.poTypeCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string giftMessage {
            get {
                return this.giftMessageField;
            }
            set {
                this.giftMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class packListData {
        
        private string packslipTemplateField;
        
        /// <remarks/>
        public string packslipTemplate {
            get {
                return this.packslipTemplateField;
            }
            set {
                this.packslipTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum poTypeCode {
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        issue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class lineItem {
        
        private string lineItemIdField;
        
        private string orderLineNumberField;
        
        private string merchantLineNumberField;
        
        private string qtyOrderedField;
        
        private string unitOfMeasureField;
        
        private string descriptionField;
        
        private string description2Field;
        
        private string merchantSKUField;
        
        private string vendorSKUField;
        
        private decimal unitCostField;
        
        private string shippingCodeField;
        
        private string requestedArrivalDateField;
        
        private poLineData poLineDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string lineItemId {
            get {
                return this.lineItemIdField;
            }
            set {
                this.lineItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string orderLineNumber {
            get {
                return this.orderLineNumberField;
            }
            set {
                this.orderLineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string merchantLineNumber {
            get {
                return this.merchantLineNumberField;
            }
            set {
                this.merchantLineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string qtyOrdered {
            get {
                return this.qtyOrderedField;
            }
            set {
                this.qtyOrderedField = value;
            }
        }
        
        /// <remarks/>
        public string unitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string description2 {
            get {
                return this.description2Field;
            }
            set {
                this.description2Field = value;
            }
        }
        
        /// <remarks/>
        public string merchantSKU {
            get {
                return this.merchantSKUField;
            }
            set {
                this.merchantSKUField = value;
            }
        }
        
        /// <remarks/>
        public string vendorSKU {
            get {
                return this.vendorSKUField;
            }
            set {
                this.vendorSKUField = value;
            }
        }
        
        /// <remarks/>
        public decimal unitCost {
            get {
                return this.unitCostField;
            }
            set {
                this.unitCostField = value;
            }
        }
        
        /// <remarks/>
        public string shippingCode {
            get {
                return this.shippingCodeField;
            }
            set {
                this.shippingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string requestedArrivalDate {
            get {
                return this.requestedArrivalDateField;
            }
            set {
                this.requestedArrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public poLineData poLineData {
            get {
                return this.poLineDataField;
            }
            set {
                this.poLineDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class poLineData {
        
        private unitShippingWeight unitShippingWeightField;
        
        private string lineReqShipDateField;
        
        private string giftMessageField;
        
        /// <remarks/>
        public unitShippingWeight unitShippingWeight {
            get {
                return this.unitShippingWeightField;
            }
            set {
                this.unitShippingWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string lineReqShipDate {
            get {
                return this.lineReqShipDateField;
            }
            set {
                this.lineReqShipDateField = value;
            }
        }
        
        /// <remarks/>
        public string giftMessage {
            get {
                return this.giftMessageField;
            }
            set {
                this.giftMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class unitShippingWeight {
        
        private string weightUnitField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string weightUnit {
            get {
                return this.weightUnitField;
            }
            set {
                this.weightUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class personPlace {
        
        private string name1Field;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string emailField;
        
        private string dayPhoneField;
        
        private string partnerPersonPlaceIdField;
        
        private personPlaceData personPlaceDataField;
        
        private string personPlaceIDField;
        
        /// <remarks/>
        public string name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string dayPhone {
            get {
                return this.dayPhoneField;
            }
            set {
                this.dayPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string partnerPersonPlaceId {
            get {
                return this.partnerPersonPlaceIdField;
            }
            set {
                this.partnerPersonPlaceIdField = value;
            }
        }
        
        /// <remarks/>
        public personPlaceData personPlaceData {
            get {
                return this.personPlaceDataField;
            }
            set {
                this.personPlaceDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string personPlaceID {
            get {
                return this.personPlaceIDField;
            }
            set {
                this.personPlaceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class personPlaceData {
        
        private string companyNameField;
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum hubOrderType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("stand alone")]
        standalone,
        
        /// <remarks/>
        reissue,
        
        /// <remarks/>
        resend,
    }
}
